server:
  sessionTimeout: 1800
spring:
  jpa.properties:
      hibernate:
        dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect
        hbm2ddl.auto: update
        format_sql: true
        show_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  profiles.active: dev

